### PR TITLE
Fix WebSocket crash when HTMX sends null header values

### LINKED ISSUE #855: [BUG]
**Describe the bug**
Since v0.13.2 (PR #853), `_wrap_ws` in `core.py` wraps WebSocket `HEADERS` in Starlette's `Headers()` object:

```python
hdrs = Headers({k.lower():v for k,v in data.pop('HEADERS', {}).items()})
```

Starlette's `Headers()` constructor calls `.encode("latin-1")` on every value. When HTMX's WebSocket extension sends messages with `null` header values (e.g. `HX-Trigger: null`, which is normal when there is no triggering element), this crashes with:

```
AttributeError: 'NoneType' object has no attribute 'encode'
```

Prior to #853, headers were stored in a plain dict which handled `None` values without issue.

**Minimal Reproducible Example**

```python
from fasthtml.common import *

app, rt = fast_app(exts=["ws"])

@rt("/")
def get():
    return Div(
        Form(
            Input(name="msg", placeholder="Type here..."),
            id="form",
            ws_send=True,
        ),
        Div(id="output"),
        hx_ext="ws",
        ws_connect="/ws",
    )

@app.ws("/ws")
async def _(data, send):
    await send(Div(f"Got: {data.get('msg', '')}", id="output"))

serve()
```

Steps to reproduce:
1. Run the app and open it in a browser
2. Type text and press Enter to submit the form
3. Observe the server crash with `AttributeError: 'NoneType' object has no attribute 'encode'`

This occurs because HTMX includes headers like `HX-Trigger` with `null` values in the WebSocket JSON payload:

```json
{
  "msg": "hello",
  "HEADERS": {
    "HX-Request": "true",
    "HX-Trigger": null,
    "HX-Trigger-Name": null,
    "HX-Target": "output"
  }
}
```

**Expected behavior**
WebSocket messages with `null` header values should be handled gracefully without crashing. The fix is to filter out `None` values before constructing the `Headers` object:

```python
hdrs = Headers({k.lower():v for k,v in data.pop('HEADERS', {}).items() if v is not None})
```

**Environment Information**
- fastlite version: 0.2.4
- fastcore version: 1.12.34
- fasthtml version: 0.13.3

**Confirmation**
- [x] I have read the FAQ (https://docs.fastht.ml/explains/faq.html)
- [x] I have provided a minimal reproducible example
- [x] I have included the versions of fastlite, fastcore, and fasthtml
- [x] I understand that this is a volunteer open source project with no commercial support.

**Additional context**
The regression was introduced in PR #853 (commit d17be3c), which changed the header handling from a plain dict to Starlette `Headers()` to fix header key lookup (#852). The fix for #852 is correct, but `None` filtering was missed.

Current workaround: intercept `htmx:wsConfigSend` on the client side to replace `null` values with empty strings before sending.

### PR DESCRIPTION
**Pull request by aleph-ra**
**Related Issue**
Fixes #855

**Proposed Changes**
Filter out `None` values before constructing Starlette `Headers()` in `_wrap_ws` (`core.py:270`). This fixes the `AttributeError: 'NoneType' object has no attribute 'encode'` crash that occurs when HTMX's WebSocket extension sends `null` header values (e.g. `HX-Trigger: null`).

```python
# Before
hdrs = Headers({k.lower():v for k,v in data.pop('HEADERS', {}).items()})

# After
hdrs = Headers({k.lower():v for k,v in data.pop('HEADERS', {}).items() if v is not None})
```

This preserves the case-insensitive header lookup behavior introduced in #853 while gracefully handling `null` values.

**Types of changes**
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Checklist**
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I am aware that this is an nbdev project, and I have edited, cleaned, and synced the source notebooks instead of editing .py or .md files directly.

**Additional Information**
Regression introduced in #853 (commit d17be3c). The fix for #852 correctly switched from a plain dict to Starlette `Headers()` for case-insensitive lookup, but missed that HTMX sends `null` values for headers like `HX-Trigger` and `HX-Trigger-Name` when there is no triggering element. Starlette's `Headers()` constructor calls `.encode("latin-1")` on every value, which raises `AttributeError` on `None`.

### CODE REVIEW

**Comment by jph00** [comment]
Thanks! :)
